version: '3.8'

services:
  web:
    image: node:23.3.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"